### ISSUE TITLE
state.list is not being updated when CREATE method is used

### ISSUE THREAD

**Issue by tonymihay** [JiriChara/vuex-crud#18] opened 2018-05-14 21:21 UTC
Hi @JiriChara,

I've noticed that the `state.list ` object is being updated only when an item is deleted or updated, but not when created. Because of this my list is not being rerendered after an item is added.

I gues the code below should be added in the createSuccess callback of createMutations.js in order to fix this issue. 

```
const listIndex = state.list.indexOf(id);

if (listIndex < 0) {
  Vue.set(state.list, state.list.length, id);
} 
```

**Comment by JiriChara** [comment] 2018-05-15 16:13
Hey @tonymihay,

this is done by design. If you are currently dispaying a list of resources that are paginated and sorted in certain way, you probably don't want that newly created resource just appears on the bottom, because you might not be sure if it belongs there. If you need to update the list of resources displayed, you have to call `fetchList` right after the `create`.

**Comment by JiriChara** [comment] 2018-05-17 13:59
Closing this for now.

**Closed by JiriChara** 2018-05-17 13:59 UTC
